name: Release to NPM
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - name: Set version
        run: |
            yarn version --no-commit-hooks --no-git-tag-version \
            --new-version ${{ steps.get_version.outputs.version-without-v }}
      - run: yarn publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
